# Generated by Django 6.0 on 2026-01-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0004_breakingnews_alter_todo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="model_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
